### PR TITLE
Fixes for multi select in tree

### PR DESCRIPTION
**Pull request by priemd**
Fixes:
- Revert 2d click behavior to what is was prior
- Check if selections > 0 in OnSelectionChange to resolve prop grid not showing issues
- Fix highlighting of deeply nested models

### CODE REVIEW

**Comment by keithsw1111** [comment]
Create group is still broken

**Comment by keithsw1111** [comment]
click on a model on layout, ctrl click a second model ... the second model does not highlight on layout but it does in the list and the panels all blank out ... that also seems wrong.

**Comment by keithsw1111** [comment]
Should I just reverse all these changes out ... they seem to be more trouble than they are worth right now.

**Comment by priemd** [comment]
You’re the boss, your call. I did a ton of testing on MacOS and could never recreate the group issues that you are seeing on Windows, I shared a video and a gif.  I am happy to continue digging in now that I know this seems to only be a problem outside of macOS but as I said earlier I’m sorry but this probably won’t be until tomorrow.

**Comment by keithsw1111** [comment]
I believe I have unwound all the changes from the master branch and moved all the pending changes into another public branch where it can continue to be worked on until we are all happy with it.

**Pull request merged**
