### PR TITLE
Add support for Shifting color palette

### PR DESCRIPTION
**Pull request by ClutchplateDude**
This PR adds the ability to shift colors in either direction (in addition to just reversing it). It also adds three new icons to support this feature.
image

Fixes Issue #4154

### CODE REVIEW

**Comment by keithsw1111** [comment]
I see no WXS file.

**Comment by ClutchplateDude** [comment]
> I see no WXS file.

Oh. I was wondering how the UI is edited, but didn't see that.... my bad. What tool is used to create/edit these? Is this something I can do in Visual Studio on Windows? Let me look into that.

**Comment by ClutchplateDude** [comment]
Ok, @keithsw1111, sorry about not knowing about wxsmith. I re-did the changes and they now have a wxs file.

**Comment by dkulp** [comment]
Can I ask what those icons will look like in dark mode?

**Comment by ClutchplateDude** [comment]
Currently they look the same, just like the Reverse button did before this change.
image
If there is a way to change these based on dark mode, I'm happy to add ones. I don't see any reference to dark mode in `BitmapCache.cpp`.

**Comment by ClutchplateDude** [comment]
@dkulp @keithsw1111  Is there are dev email list or group where you all discuss code changes? Is there a doc for new contributors beyond the CONTRIBUTING.md on the repo that goes into more detail about the code base? As a new contributor there are things I've run into that might help others that I could document. 
Also, with a change like this, am I responsible for updating the manual? If so, how?

**Comment by AzGilrock** [comment]
Nope there is no list or group.  We rarely discuss code changes anymore.  Years ago we used Trello but not sure anyone is active.  I think I had trouble finding it last time I looked.  There isn't much more than the readme's for each OS.  I don't even know who updates the user manual or how its managed.

**Pull request merged**
