### PR TITLE
Added Right Click Ping controller Option To Setup Tab

### PR DESCRIPTION
**Pull request by computergeek1507**

### CODE REVIEW

**Comment by keithsw1111** [comment]
Rather than checking for multicast ... doesnt output have a method that returns whether or not the output supports ping?

**Comment by computergeek1507** [comment]
Currently The SerialOutput Class CanPing() method returns true. I didn't know if this was a mistake or if "Ping" means xLights supports communication(outuput) with the device in general. I didn't find anywhere in xLights that it was used but I didn't know about xSchedule.

image

**Comment by keithsw1111** [comment]
Ping on serial validated that the port is open or can be opened. Ok so it isn’t a real ping but it does check the output exists and works. So yes that is correct.

**Comment by computergeek1507** [comment]
I updated it to "Ping" all pingable controllers

**Pull request merged**
