### PR TITLE
Enable timeline icon for galaxy effect / bug fix

### PR DESCRIPTION
**Pull request by KMojek**
Tom BetGeorge requested this earlier today on FB and a few others liked it. The post has since been deleted and Tom reached out to Keith directly instead. From what I can tell, the galaxy effect has never had an icon since Gil added it back in 2015. It seems like a harmless change.

I also included a small bug fix for #1450 in this branch.

### CODE REVIEW

**Comment by KMojek** [comment]
Ah okay, SuperStar was before my time. 😃 If there are reasons for keeping some without icons, fine with me.

**Comment by AzGilrock** [comment]
Well I'm not sure I'm opposed to it I'll need to see what it looks like.  Currently it does end up displaying just like a Morph so it's hard to tell which is which so it might be a good thing.  I'd just make sure it's displaying the tiny icon like Shockwave does.

**Comment by AzGilrock** [comment]
Yeah that looks good.  Fan probably needs the same thing.  Morph is probably ok without it cause everyone expects it to look that way.

**Comment by KMojek** [comment]
Okay, updated fan with the same change.

**Pull request merged**
