### PR TITLE
Initial release Easylights controller communication

### PR DESCRIPTION
**Pull request by jhinklejr**
Release of EasyLights Controller config data communication

### CODE REVIEW

**Comment by keithsw1111** [comment]
A few changes before we can merge.

Can you remove the library.
Can you explain your thinking behind the reset controller function?
Can we get rid of the //************************** surrounding your code ... it is just clutter
Can we remove the change to the platform SDK version in vcxproj
Can we remove your .user file
How sure are you the #pragmas are going to work on LInux and OSX?

**Comment by jhinklejr** [comment]
See Below

**Comment by jhinklejr** [comment]
Keith:

 

I went to remove the library – I confused – the xlights.lib – I thought you meant that one – is not in my fork directory.

 

What library are your referring to?

 

Thanks.

 

Joe

**Comment by AzGilrock** [comment]
Probably this one:
image

**Comment by keithsw1111** [comment]
Cant you reset and upload in the one action ... if necessary merge the inputs and outputs into a single upload like we had to do with the pixlite because of limitations in that controller. Having a separate reset is odd.

**Comment by keithsw1111** [comment]
As the developer you need to do the legwork as much as possible to check cross platform support. Dan/Chris will deal with some oddities but they expect the code to be written for cross platform.

**Comment by keithsw1111** [comment]
I use VS 2017 as well ... yet my SDK seems more current than yours ... we dont want to be going backwards ... or just leave that line out when you check in.

**Pull request merged**
