### PR TITLE
Timeline zooming centered on mouse marker (QoxL)

### PR DESCRIPTION
**Pull request by hoodlumj3**
#3989 

hope i'm doing this correctly, this is my first ever PR

### CODE REVIEW

**Comment by keithsw1111** [comment]
I dont see the wxs file? Did you not use codeblocks? If not then all your UI edits will get lost the next time someone edits the panel.

**Comment by hoodlumj3** [comment]
@keithsw1111 nice catch, appologies latest commit now includes the wxSmith file

**Comment by AzGilrock** [comment]
That StaticText6 object can be set to member="No" unless you need to programmatically change the text later.  I believe the default should have been No so you must have specifically changed it to Yes.  When its No it defines it locally in the constructor of the cpp file instead of needing to be in the header.  Not a big deal just pointing it out since it looks like it was changed from the defaults.

**Comment by hoodlumj3** [comment]
@AzGilrock I did wonder why it was sitting out in the class instead of local all of a sudden - thx for the hot tip, I shall correct for consistency.

**Pull request merged**
