### PR TITLE
Update falcon.xcontroller

### PR DESCRIPTION
**Pull request by TrekErs**

### CODE REVIEW

**Comment by TrekErs** [comment]
fix #3211

**Comment by computergeek1507** [comment]
I don't think the V4 should inherit the V2\V3 base configuration. The V4 supports a different feature set and different pixel types

**Comment by TrekErs** [comment]
I wasn’t sure either so my first fix was the same way you fixed it. Keith happened to pop into the zoom room and confirmed that it should incorporate the base settings.  Of course he didn’t put it quite so delicately.  :)

**Comment by computergeek1507** [comment]
If he wants to incorporate the base falcon type, then the v3 settings need to be abstracted out to another layer. The base settings currently has the GECE pixel types and the universe/channel count of the V3.

**Comment by TrekErs** [comment]
I did a little testing and including the BaseFalconSettings appears to work since the protocols and max input universes are defined in the BaseV4FalconSettings those appear to overwrite the BaseFalconSettings.  Not saying one way is right or wrong, just wanted to share what I found.

While testing I did notice that the protocols with spaces (lines 190 192 195) do not appear as available protocols.  But this is something I do not know how to fix or even if it is an issue.

**Pull request closed without merging**
