### PR TITLE
Tree horizontal

### PR DESCRIPTION
**Pull request by merryoncherry**
For #3258 - Tree Model gets horizontal strands

### CODE REVIEW

**Comment by AzGilrock** [comment]
I kinda don't like the new attribute being used as a string everywhere requiring string comparisons.  The Matrix used a string but only because it was the "DisplayAs" field which was already a string.  Most other attributes use integers to store the value in the XML.  See how the TOP_BOT_LEFT_RIGHT variable in the MatrixModel is used.  The strings are only used for display purposes but the rest of the program uses the enumeration values and its a wxEnumProperty.  Its not a super big deal I'm just always thinking of what's faster and strings are usually slower.

**Comment by merryoncherry** [comment]
> I kinda don't like the new attribute being used as a string everywhere requiring string comparisons.

I would be happy to follow the other example you cite and switch to integer.  Let me try it this afternoon.  Gotta say, I was surprised how much information is sometimes stored in the "Display As" field, like matrix direction for matrix, degrees for tree...

The argument for using the string in the xml is for any other tool that reads the xml, if any, or if someone reorders the enum, or anything like that, then it will still read properly.

**Comment by AzGilrock** [comment]
Yes I thought of that as well but we probably have tons of items that are tied to enum orders already.  I'm used to working with real time embedded code.  I'd wait and see if any other dev's have an opinion.  I'm not going to make a fuss about it if it stays as is.

**Comment by computergeek1507** [comment]
It's also not a "hard rule" I am sure you can find instances when I have used string compares.

**Comment by computergeek1507** [comment]
all the examples I found we convert bools to strings for saving

**Comment by merryoncherry** [comment]
Seems the XML document uses string for everything... but we still get to decide if we want "0"/"1" or "Horizontal"/"Vertical".

In favor of text (possibly others, this is just what I see doing a quick skim of rgbeffects.xml):
layout="horizontal", type="ranges", bufferstyle="Default", type="subbuffer", StartSide="T", Dir="R", StringType="RGB Nodes", StarStartLocation="Bottom Ctr-CCW", CandyCaneReverse="false"

In favor of numbers (possibly others, as noted):
Antialias="1" (comes from "Pixel Style" enum)
Locked="1", selected="0"

Antialias jumps out as the most elaborate enum I found.  The numbers version includes a lot of code like this, rather than string compares, but it is easy enough to do.
 wxString::Format(wxT("%i"), (int)_pixelStyle)

Whatever is consensus, let me know.

**Pull request merged**
