### PR TITLE
Parallel_for in RenderBuffer::CopyNodeColorsToPixels causes bad renders

### PR DESCRIPTION
**Pull request by merryoncherry**
See #3740 for a description of the resulting problem.

The easy fix is to take out the parallel_for.  I didn't notice any performance difference in a practical setting (my 2022 show bulk render), but it fixed a number of glitchy effects.

### CODE REVIEW

**Comment by dkulp** [comment]
I think the other option would be to change "std::vector<bool> &done" to "std::vector<uint8_t> &done"

**Comment by merryoncherry** [comment]
I will be happy to try that.

**Comment by merryoncherry** [comment]
Right, vector<bool> is special and has the threads fighting for values in the same byte.  Otherwise it's possibly fine (on x86).
It seems to work on my simple test case from the original issue.  I will try a more extensive test next.

**Comment by merryoncherry** [comment]
Seems to work as well in the quick tests, updating the PR.

**Comment by merryoncherry** [comment]
Thanks for the review @dkulp

**Pull request merged**
